title: Onebit
titleico: 
email: mail@loefairy.top
author: ğŸ’‚â€â™‚ï¸XX025
description: >- # this means to ignore newlines until "baseurl:"
  ä½ æ‰æ˜¯é‚£ä¸ªç©¿è¶Šç†Šç†Šå¤§ç«å†²å‡ºè¿™é‡Œçš„äººã€Šå½“ä½ åƒé¸Ÿé£å¾€ä½ çš„å±±ã€‹
baseurl: ""
url: ""
github_username: xx025
weibo_username: xx052
weibo_username_id: "rmrb"
theme: minima
plugins:
  - jekyll-feed
permalink: /:short_year:i_month:i_day:title
show_excerpts: True


plugins: [jekyll-paginate]
paginate_path: "/blog/page:num/"
paginate: 5

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


