title: xx025
titleico: favicon
email: mail@loefairy.top
author: ğŸ’‚â€â™‚ï¸xx025
description: >- # this means to ignore newlines until "baseurl:"
  "ä½ æ‰æ˜¯é‚£ä¸ªç©¿è¶Šç†Šç†Šå¤§ç«å†²å‡ºè¿™é‡Œçš„äºº"ã€Šå½“ä½ åƒé¸Ÿé£å¾€ä½ çš„å±±ã€‹
baseurl: "" 
url: ""
github_username: xx025
weibo_username: xx052
weibo_username_id: 'rmrb' 
theme: minima
plugins:
  - jekyll-feed

# è‡ªå®šä¹‰
permalink: /:title:output_ext
show_excerpts: True
